# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=datetime.datetime(2017, 4, 26, 21, 12, 51, 780621, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
