# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date posted'),
        ),
    ]
